POST http://localhost:{{port}}/doLogin
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

###
GET http://localhost:{{port}}/home
Accept: application/json

###

GET http://localhost:{{port}}/home/9012321
Accept: application/json

